
import React, { useState } from 'react';
import { Timeframe, NarrativePaneInfo } from '../types';
import { DASHBOARD_DATA } from '../constants';
import MetricCard from '../components/MetricCard';
import ConcernsChart from '../components/ConcernsChart';
import TopProcedures from '../components/TopProcedures';
import TreatmentTrendsChart from '../components/TreatmentTrendsChart';
import PatientExperienceChart from '../components/PatientExperienceChart';
import WorkflowQuality from '../components/WorkflowQuality';
import MarketingOpportunities from '../components/MarketingOpportunities';
import SalesExcellence from '../components/SalesExcellence';
import AnalysisFields from '../components/AnalysisFields';
import NarrativePane from '../components/NarrativePane';
import { Button } from '../components/ui/button';
import { cn } from '../lib/utils';
import { ChevronDown } from 'lucide-react';

const DashboardPage: React.FC = () => {
  const [timeframe, setTimeframe] = useState<Timeframe>('Monthly');
  const [narrativePane, setNarrativePane] = useState<NarrativePaneInfo>({
    isOpen: false,
    title: '',
    content: '',
  });

  const data = DASHBOARD_DATA[timeframe];

  const handleOpenNarrative = (title: string) => {
    setNarrativePane({
      isOpen: true,
      title: title,
      content: `Detailed analysis for ${title}. This report provides an in-depth look at the underlying data, trends, and actionable insights. [Content to be generated by Gemini API later]`,
    });
  };

  const handleCloseNarrative = () => {
    setNarrativePane({ ...narrativePane, isOpen: false });
  };

  const DashboardHeader = () => (
    <header className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Insights Dashboard</h1>
        <p className="text-muted-foreground mt-1">Real-time overview of consultation data</p>
      </div>
      <div className="flex items-center space-x-4 mt-4 sm:mt-0">
        <div className="flex items-center bg-secondary rounded-lg p-1 text-sm font-medium">
          <Button
            onClick={() => setTimeframe('Monthly')}
            variant="ghost"
            size="sm"
            className={cn("w-20", timeframe === 'Monthly' && 'bg-card text-card-foreground shadow-sm')}
          >
            Monthly
          </Button>
          <Button
            onClick={() => setTimeframe('Weekly')}
            variant="ghost"
            size="sm"
            className={cn("w-20", timeframe === 'Weekly' && 'bg-card text-card-foreground shadow-sm')}
          >
            Weekly
          </Button>
        </div>
        <div className="relative">
          <select className="appearance-none bg-card border border-input rounded-md shadow-sm h-9 pl-3 pr-8 text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-ring">
            <option>Last 30 Days</option>
            <option>Last 60 Days</option>
            <option>Last 90 Days</option>
          </select>
          <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground pointer-events-none" />
        </div>
      </div>
    </header>
  );

  return (
    <div className="p-4 sm:p-6 lg:p-8">
      <DashboardHeader />
      
      <main>
        {/* High-Level Metrics */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {data.highLevelMetrics.map((metric) => (
            <MetricCard
              key={metric.title}
              title={metric.title}
              value={metric.value}
              tooltipText="This metric is calculated based on an aggregation of all consultation transcripts for the selected time period."
              onClick={() => handleOpenNarrative(metric.title)}
            />
          ))}
        </div>
        
        {/* Main Dashboard Grid */}
        <div className="grid grid-cols-1 xl:grid-cols-12 gap-6">
            <div className="xl:col-span-4">
              <ConcernsChart 
                data={data.concerns} 
                onSliceClick={(name) => handleOpenNarrative(`Concern: ${name}`)}
              />
            </div>
            <div className="xl:col-span-8">
                <TreatmentTrendsChart 
                data={data.treatmentTrends} 
                onBarClick={(payload) => handleOpenNarrative(`Treatment Trend: ${payload.name}`)}
              />
            </div>
            <div className="xl:col-span-12">
              <PatientExperienceChart
                satisfactionData={data.satisfactionScores}
                educationData={data.educationScores}
                onPointClick={(payload) => handleOpenNarrative(`Patient Experience - ${payload.month}`)}
              />
            </div>
            <div className="xl:col-span-3">
              <TopProcedures 
                data={data.topProcedures} 
                onItemClick={(name) => handleOpenNarrative(`Top Procedure: ${name}`)}
              />
            </div>
            <div className="xl:col-span-5">
              <SalesExcellence 
                scores={data.salesExcellence}
                onScoreClick={(skill) => handleOpenNarrative(`Sales Excellence: ${skill}`)}
              />
            </div>
            <div className="xl:col-span-4">
              <WorkflowQuality 
                data={data.workflowQuality}
                onItemClick={(title) => handleOpenNarrative(`Workflow Quality: ${title}`)}
              />
            </div>
            <div className="xl:col-span-7">
              <MarketingOpportunities
                demographicsData={data.demographics}
                seasonalData={data.seasonalTrends}
                onItemClick={(title) => handleOpenNarrative(title)}
              />
            </div>
            <div className="xl:col-span-5">
              <AnalysisFields 
                insights={data.analysisFields}
                onItemClick={(category) => handleOpenNarrative(`Analysis: ${category}`)}
              />
            </div>
        </div>
      </main>

      <NarrativePane
        isOpen={narrativePane.isOpen}
        title={narrativePane.title}
        content={narrativePane.content}
        onClose={handleCloseNarrative}
      />
    </div>
  );
};

export default DashboardPage;